name: Deploy Kuepass Standalone

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Copy Standalone to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # We send the standalone folder and static files
          source: ".next/standalone/*,.next/static/*,public/*"
          target: "~/kuepassApp/deploy"
          strip_components: 0

      - name: Restart App on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Move files to the right spot and restart PM2
            cp -r ~/kuepassApp/deploy/.next/standalone/* ~/kuepassApp/
            cp -r ~/kuepassApp/deploy/.next/static ~/kuepassApp/.next/
            cp -r ~/kuepassApp/deploy/public ~/kuepassApp/
            pm2 restart kuepass-frontend || pm2 start ~/kuepassApp/server.js --name "kuepass-frontend"
